package graphics.user;

import graphics.SAveChanges;
import project.first.project;

import javax.swing.*;
import java.awt.*;

public class changeInfo extends javax.swing.JFrame {


    private static Boolean submitChecked=null;


    public changeInfo() {
        initComponents();

        if (project.useraccount.getSeller() == null)
        {
            institute_txt.setEnabled(false);
            factory_txt.setEnabled(false);
            workShop_txt.setEnabled(false);
        }

        putInfo();

        setResizable(false);
        setVisible(true);

        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                JFrame j=new JFrame();
                JOptionPane.showMessageDialog(j,"please enter after any changes you made for confirmation");
            }
        });
    }

    //======================================================================

    public void putInfo()
    {
        name_txt.setText(project.useraccount.getName());
        family_txt.setText(project.useraccount.getFamilyName());
        phone_txt.setText(project.useraccount.getPhoneNum());
        pass_txt.setText(project.useraccount.getPassword());
        ID_txt.setText(project.useraccount.getId());
        email_txt.setText(project.useraccount.getEmail());

        if (project.useraccount.getSeller() != null)
        {
            factory_txt.setText(project.useraccount.getSeller().getFactoryName());
            institute_txt.setText(project.useraccount.getSeller().getInstituteName());
            workShop_txt.setText(project.useraccount.getSeller().getWorkShopName());
        }
    }

    //======================================================================

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        name_label = new javax.swing.JLabel();
        family_label = new javax.swing.JLabel();
        email_label = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        id_label = new javax.swing.JLabel();
        pass_label = new javax.swing.JLabel();
        institute_lbl = new javax.swing.JLabel();
        workShop_lbl = new javax.swing.JLabel();
        factory_lbl = new javax.swing.JLabel();
        name_txt = new javax.swing.JTextField();
        family_txt = new javax.swing.JTextField();
        email_txt = new javax.swing.JTextField();
        phone_txt = new javax.swing.JTextField();
        ID_txt = new javax.swing.JTextField();
        pass_txt = new javax.swing.JTextField();
        institute_txt = new javax.swing.JTextField();
        workShop_txt = new javax.swing.JTextField();
        factory_txt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        name_label.setText("name");

        family_label.setText("family name");

        email_label.setText("email");

        jLabel4.setText("phone number");

        id_label.setText("ID");

        pass_label.setText("password");

        institute_lbl.setText("institute");

        workShop_lbl.setText("work shop");

        factory_lbl.setText("factory");

        name_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name_txtActionPerformed(evt);
            }
        });

        family_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                family_txtActionPerformed(evt);
            }
        });

        email_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                email_txtActionPerformed(evt);
            }
        });

        phone_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phone_txtActionPerformed(evt);
            }
        });

        ID_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ID_txtActionPerformed(evt);
            }
        });

        pass_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pass_txtActionPerformed(evt);
            }
        });

        institute_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                institute_txtActionPerformed(evt);
            }
        });

        workShop_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                workShop_txtActionPerformed(evt);
            }
        });

        factory_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                factory_txtActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(102, 255, 102));
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(27, 27, 27)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                .addComponent(email_label)
                                                                                .addComponent(name_label))
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addGap(2, 2, 2)
                                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(id_label)
                                                                                        .addComponent(factory_lbl))))
                                                                .addGap(4, 4, 4))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(institute_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(13, 13, 13)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(ID_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(email_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(name_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(18, 18, 18)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(factory_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(institute_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                .addGap(33, 33, 33)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(family_label)
                                                        .addComponent(jLabel4)
                                                        .addComponent(pass_label)
                                                        .addComponent(workShop_lbl)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jButton1)
                                                .addGap(20, 20, 20)))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(workShop_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(pass_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(phone_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(family_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(89, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(name_label)
                                        .addComponent(family_label)
                                        .addComponent(name_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(family_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(email_label)
                                        .addComponent(jLabel4)
                                        .addComponent(email_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(phone_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(52, 52, 52)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(id_label)
                                        .addComponent(pass_label)
                                        .addComponent(ID_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(pass_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(53, 53, 53)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(workShop_lbl)
                                        .addComponent(institute_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(workShop_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(institute_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(factory_lbl)
                                        .addComponent(factory_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                                .addComponent(jButton1)
                                .addGap(20, 20, 20))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>

    private void name_txtActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            project.changeInformation( "name" ,name_txt.getText());
        }catch (Exception e)
        {
            JFrame j=new JFrame();
            JOptionPane.showMessageDialog(j,e.getMessage());
        }

    }

    private void family_txtActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            project.changeInformation( "family" ,family_txt.getText());
        }catch (Exception e)
        {
            JFrame j=new JFrame();
            JOptionPane.showMessageDialog(j,e.getMessage());
        }
    }

    private void email_txtActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            project.changeInformation( "email" ,email_txt.getText());
        }catch (Exception e)
        {
            JFrame j=new JFrame();
            JOptionPane.showMessageDialog(j,e.getMessage());
        }
    }

    private void phone_txtActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            project.changeInformation( "phone" ,phone_txt.getText());
        }catch (Exception e)
        {
            JFrame j=new JFrame();
            JOptionPane.showMessageDialog(j,e.getMessage());
        }
    }

    private void ID_txtActionPerformed(java.awt.event.ActionEvent evt) {
        ID_txt.setText("cannot be changed !");
        ID_txt.setBackground(Color.RED);
        ID_txt.setForeground(Color.BLACK);
    }

    private void pass_txtActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            project.changeInformation( "pass" ,pass_txt.getText());
        }catch (Exception e)
        {
            JFrame j=new JFrame();
            JOptionPane.showMessageDialog(j,e.getMessage());
        }
    }

    private void institute_txtActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            project.changeInformation( "institute" ,institute_txt.getText());
        }catch (Exception e)
        {
            JFrame j=new JFrame();
            JOptionPane.showMessageDialog(j,e.getMessage());
        }
    }

    private void workShop_txtActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            project.changeInformation( "work" ,workShop_txt.getText());
        }catch (Exception e)
        {
            JFrame j=new JFrame();
            JOptionPane.showMessageDialog(j,e.getMessage());
        }
    }

    private void factory_txtActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            project.changeInformation( "factory" ,factory_txt.getText());
        }catch (Exception e)
        {
            JFrame j=new JFrame();
            JOptionPane.showMessageDialog(j,e.getMessage());
        }
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        project.saving();
        this.dispose();
    }


    // Variables declaration - do not modify
    private javax.swing.JTextField ID_txt;
    private javax.swing.JLabel email_label;
    private javax.swing.JTextField email_txt;
    private javax.swing.JLabel factory_lbl;
    private javax.swing.JTextField factory_txt;
    private javax.swing.JLabel family_label;
    private javax.swing.JTextField family_txt;
    private javax.swing.JLabel id_label;
    private javax.swing.JLabel institute_lbl;
    private javax.swing.JTextField institute_txt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel name_label;
    private javax.swing.JTextField name_txt;
    private javax.swing.JLabel pass_label;
    private javax.swing.JTextField pass_txt;
    private javax.swing.JTextField phone_txt;
    private javax.swing.JLabel workShop_lbl;
    private javax.swing.JTextField workShop_txt;
    // End of variables declaration


    //========================

    public static void setSubmitChecked(boolean submitChecked) {
        changeInfo.submitChecked = submitChecked;
    }

    //========================
}
