package graphics.user.buyer;


import graphics.SAveChanges;
import graphics.mainPage;
import graphics.products.showAllProducts;
import graphics.user.changeInfo;
import graphics.user.showINFO;
import project.first.BuyerAccess;
import project.first.project;

import javax.swing.*;

public class mainMenu extends javax.swing.JFrame {

    /**
     * Creates new form mainMenu
     */
    public mainMenu() {
        initComponents();

        setResizable(false);
        this.setLocationRelativeTo(null);//location of the frame
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        top_label = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        changeInfo_btn = new javax.swing.JToggleButton();
        seeProduct_btn = new javax.swing.JToggleButton();
        basket_btn = new javax.swing.JToggleButton();
        rate_btn = new javax.swing.JToggleButton();
        moneyInSt = new javax.swing.JToggleButton();
        logOut = new javax.swing.JToggleButton();

        setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 153));

        top_label.setBackground(new java.awt.Color(255, 204, 204));
        top_label.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        top_label.setForeground(new java.awt.Color(0, 255, 255));
        top_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        top_label.setText("Buyer");

        jToggleButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ES\\Pictures\\project\\7.png")); // NOI18N
        jToggleButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jToggleButton1.setPreferredSize(new java.awt.Dimension(70, 70));
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jLayeredPane1.setBackground(new java.awt.Color(102, 102, 255));
        jLayeredPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 4));
        jLayeredPane1.setForeground(new java.awt.Color(0, 102, 102));

        changeInfo_btn.setBackground(new java.awt.Color(0, 153, 153));
        changeInfo_btn.setText("change info");
        changeInfo_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeInfo_btnActionPerformed(evt);
            }
        });

        seeProduct_btn.setBackground(new java.awt.Color(0, 102, 102));
        seeProduct_btn.setText("see products");
        seeProduct_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seeProduct_btnActionPerformed(evt);
            }
        });

        basket_btn.setBackground(new java.awt.Color(51, 102, 255));
        basket_btn.setText("see basket");
        basket_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                basket_btnActionPerformed(evt);
            }
        });

        rate_btn.setBackground(new java.awt.Color(153, 51, 255));
        rate_btn.setText("rate a product");
        rate_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rate_btnActionPerformed(evt);
            }
        });

        moneyInSt.setBackground(new java.awt.Color(102, 102, 255));
        moneyInSt.setText("money in stock");
        moneyInSt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moneyInStActionPerformed(evt);
            }
        });

        logOut.setBackground(new java.awt.Color(153, 51, 255));
        logOut.setText("log out");
        logOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutActionPerformed(evt);
            }
        });

        jLayeredPane1.setLayer(changeInfo_btn, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(seeProduct_btn, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(basket_btn, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(rate_btn, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(moneyInSt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(logOut, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
                jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(logOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(moneyInSt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(rate_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(basket_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(seeProduct_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(changeInfo_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap(37, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
                jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(changeInfo_btn)
                                .addGap(36, 36, 36)
                                .addComponent(seeProduct_btn)
                                .addGap(33, 33, 33)
                                .addComponent(basket_btn)
                                .addGap(38, 38, 38)
                                .addComponent(rate_btn)
                                .addGap(38, 38, 38)
                                .addComponent(moneyInSt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                                .addComponent(logOut)
                                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(177, 177, 177)
                                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(166, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(228, 228, 228))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(top_label, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(193, 193, 193))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(top_label, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jLayeredPane1)
                                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>

    private void changeInfo_btnActionPerformed(java.awt.event.ActionEvent evt) {
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                changeInfo change_Info=new changeInfo();
            }
        });
    }

    private void seeProduct_btnActionPerformed(java.awt.event.ActionEvent evt) {
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                showAllProducts showAll=new showAllProducts();
            }
        });
    }

    private void basket_btnActionPerformed(java.awt.event.ActionEvent evt) {
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                basket Basket = new basket();
            }
        });
    }

    private void rate_btnActionPerformed(java.awt.event.ActionEvent evt) {
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                rateProduct rate_Product=new rateProduct() ;
            }
        });
    }


    private void moneyInStActionPerformed(java.awt.event.ActionEvent evt) {
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                moneyInStock money=new moneyInStock(project.useraccount.getMoneyInStock());
            }
        });
    }


    private void logOutActionPerformed(java.awt.event.ActionEvent evt) {
        project.CategoryOrganize();
        project.saving();
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                mainPage m=new mainPage();
            }
        });
        this.dispose();
    }

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                showINFO showInfo=new showINFO();
            }
        });
    }



    // Variables declaration - do not modify
    private javax.swing.JToggleButton basket_btn;
    private javax.swing.JToggleButton changeInfo_btn;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton logOut;
    private javax.swing.JToggleButton moneyInSt;
    private javax.swing.JToggleButton rate_btn;
    private javax.swing.JToggleButton seeProduct_btn;
    private javax.swing.JLabel top_label;
    // End of variables declaration
}
