package graphics.user.seller;


import account.making.Seller;
import products.Product;
import project.first.SellerAccess;

import javax.swing.*;

public class makeDiscount extends javax.swing.JFrame {

    /**
     * Creates new form makeDiscount
     */
    public makeDiscount() {
        initComponents();

        setResizable(false);
        error_lbl.setEnabled(false);
        global_btn.setEnabled(false);
        special_btn.setEnabled(false);
        code_lbl.setEnabled(false);
        extra_lbl.setEnabled(false);
        added_s.setEnabled(false);
        ok_btn.setEnabled(false);

        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        earmark_txt = new javax.swing.JTextField();
        error_lbl = new javax.swing.JLabel();
        extra_lbl = new javax.swing.JLabel();
        global_btn = new javax.swing.JToggleButton();
        special_btn = new javax.swing.JToggleButton();
        added_s = new javax.swing.JLabel();
        code_lbl = new javax.swing.JLabel();
        ok_btn = new javax.swing.JToggleButton();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("enter the earmark of the product:");

        earmark_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                earmark_txtActionPerformed(evt);
            }
        });

        error_lbl.setForeground(new java.awt.Color(255, 0, 51));
        error_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        error_lbl.setText("wrong earmark !");

        extra_lbl.setForeground(new java.awt.Color(0, 255, 51));
        extra_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        extra_lbl.setText("extra");

        global_btn.setText("global discount");
        global_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                global_btnActionPerformed(evt);
            }
        });

        special_btn.setText("special discount");
        special_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                special_btnActionPerformed(evt);
            }
        });

        added_s.setForeground(new java.awt.Color(51, 255, 0));
        added_s.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        added_s.setText("added successfully !");

        code_lbl.setForeground(new java.awt.Color(51, 0, 255));
        code_lbl.setText("code : ");

        ok_btn.setText("OK");
        ok_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ok_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(added_s, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(global_btn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 172, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(earmark_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(special_btn))
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGroup(layout.createSequentialGroup()
                                .addGap(166, 166, 166)
                                .addComponent(extra_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(192, 192, 192)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(code_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(ok_btn)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(116, 116, 116)
                                                .addComponent(error_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(88, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(error_lbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(earmark_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(extra_lbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(global_btn)
                                        .addComponent(special_btn))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(added_s, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(code_lbl))
                                .addGap(18, 18, 18)
                                .addComponent(ok_btn)
                                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>

    private void special_btnActionPerformed(java.awt.event.ActionEvent evt) {

    }

    private void global_btnActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void earmark_txtActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            Product product= SellerAccess.findEarmark(Integer.parseInt(earmark_txt.getText()));
            global_btn.setEnabled(true);
            special_btn.setEnabled(true);
            extra_lbl.setText("found !");
            extra_lbl.setEnabled(true);

        }catch (Exception e)
        {
            error_lbl.setText("wrong earmark!");
        }
    }

    private void ok_btnActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }



    // Variables declaration - do not modify
    private javax.swing.JLabel added_s;
    private javax.swing.JLabel code_lbl;
    private javax.swing.JTextField earmark_txt;
    private javax.swing.JLabel error_lbl;
    private javax.swing.JLabel extra_lbl;
    private javax.swing.JToggleButton global_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JToggleButton ok_btn;
    private javax.swing.JToggleButton special_btn;
    // End of variables declaration
}
